[package]
name = "glow"
version = "0.1.47"
authors = ["Evan Feenstra"]
edition = "2018"

[dependencies]
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.3"
futures = "0.3.0"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }
hacl-star = "0.1.0"
hex = "0.3.2"
rand = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { version = "1.0.29", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = ["full", "time"] }
tokio-tungstenite = "0.13.0"
zeroize = "1.1.1"

# [dev-dependencies]
# tokio-test = "0.3.0"

[dependencies.tungstenite]
version = "0.12.0"
default-features = false
