name: Format & Lint

on:
  pull_request:
  push:
    branches:
      - 'develop'

jobs:
  all:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn --ignore-scripts

      - name: Format
        run: yarn format-check

      - name: Lint
        run: yarn lint
